### ISSUE TITLE
move broad_sparse config from json to hydra yaml

### ISSUE THREAD

**Issue by mkutu** [precision-sustainable-ag/Field-AnnotationPipeline#21]
make a morphology folder and add a default.yaml file with: 
```yaml
broad_morphology:
  - 1 # Palmer amaranth
  - 3 # Sicklepod

sparse_morphology:
  - 2
 ```
broad_morphology = cfg.morphology.broad_morphology # List of class_ids

**Comment by mkutu** [comment]
remove unused paths in main config.yaml

**Comment by mkutu** [comment]
add morphology to the main config
```yaml
defaults:
  - override hydra/job_logging: custom # custom logging
  - morphology: morphology
  - _self_
```
